GetCredentialConfig:
  InjiCertify_GetcredentialConfig_Mosipid_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_Mosipid_01
    description: Get credential configuration
    role: noauth
    checkErrorsOnlyInResponse: true
    restMethod: get
    additionalDependencies: TC_InjiCertify_MosipID_AddCredentialConfig_01
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfigurationResult
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_1.1_all_Valid_Smoke_sid_id$"
    }'
    output: '{
    }'

  InjiCertify_GetcredentialConfig_Mosipid_without_qrSignature:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_Mosipid_02
    description: Get credential configuration
    role: noauth
    checkErrorsOnlyInResponse: true
    restMethod: get
    additionalDependencies: TC_InjiCertify_MosipID_AddCredentialConfig_14
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfigurationResult
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_empty_qrSignatureAlgo_sid_id$"
    }'
    output: '{
    }'
