services:

  # =========================
  # INJI CERTIFY
  # =========================

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./inji-certify/docker-compose/docker-compose-injistack/certify_init.sql:/docker-entrypoint-initdb.d/certify_init.sql
      - ./inji-certify/docker-compose/docker-compose-injistack/mimoto_init.sql:/docker-entrypoint-initdb.d/mimoto_init.sql
    networks:
      - conformance-net

  certify:
    image: injistack/inji-certify-with-plugins:1.0.0-alpha.1
    user: root
    ports:
      - "8090:8090"
    environment:
      container_user: mosip
      active_profile_env: default,csvdp-farmer
      SPRING_CONFIG_NAME: certify
      SPRING_CONFIG_LOCATION: /home/mosip/config/
      enable_certify_artifactory: "false"
      download_hsm_client: "false"
      mosip_certify_domain_url: http://certify-nginx:80
    volumes:
      - ./inji-certify/docker-compose/docker-compose-injistack/config/certify-default.properties:/home/mosip/config/certify-default.properties
      - ./inji-certify/docker-compose/docker-compose-injistack/config/certify-csvdp-farmer.properties:/home/mosip/config/certify-csvdp-farmer.properties
      - ./inji-certify/docker-compose/docker-compose-injistack/config/certify-mock-mdl.properties:/home/mosip/config/certify-mock-mdl.properties
      - ./inji-certify/docker-compose/docker-compose-injistack/config/certify-mdl-pdi.properties:/home/mosip/config/certify-mdl-pdi.properties
      - ./inji-certify/docker-compose/docker-compose-injistack/data/CERTIFY_PKCS12:/home/mosip/CERTIFY_PKCS12
      - ./inji-certify/docker-compose/docker-compose-injistack/config/farmer_identity_data.csv:/home/mosip/config/farmer_identity_data.csv
      - ./inji-certify/docker-compose/docker-compose-injistack/config/driving_license_mosipid.csv:/home/mosip/config/driving_license_mosipid.csv
      - ./inji-certify/docker-compose/docker-compose-injistack/config/vp_request_config.json:/home/mosip/config/vp_request_config.json
      - ./inji-certify/docker-compose/docker-compose-injistack/context/farmer-context.json:/home/mosip/context/farmer-context.json
      - ./inji-certify/docker-compose/docker-compose-injistack/context/mdl-pdi-context.json:/home/mosip/context/mdl-pdi-context.json
    networks:
      - conformance-net
    depends_on:
      - database

  certify-nginx:
    image: nginx:stable
    ports:
      - "8091:80"
    volumes:
      - ./inji-certify/docker-compose/docker-compose-injistack/certify-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./inji-certify/docker-compose/docker-compose-injistack/config/mimoto-issuers-config.json:/config/server/mimoto-issuers-config.json
      - ./inji-certify/docker-compose/docker-compose-injistack/config/mimoto-trusted-verifiers.json:/config/server/mimoto-trusted-verifiers.json
      - ./inji-certify/docker-compose/docker-compose-injistack/config/credential-template.html:/config/server/credential-template.html
      - ./inji-certify/docker-compose/docker-compose-injistack/config/vp_request_config.json:/config/server/vp_request_config.json
    networks:
      - conformance-net
    depends_on:
      - certify

  # =========================
  # INJI VERIFY
  # =========================

  verify-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inji_verify
    volumes:
      - ./inji-verify/docker-compose/db-init:/docker-entrypoint-initdb.d
    networks:
      - conformance-net

  verify-service:
    image: injistack/inji-verify-service:1.0.0-alpha.1
    container_name: verify-service
    user: root
    ports:
      - "8080:8080"
    environment:
      active_profile_env: default
      DATABASE_HOST: verify-postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: inji_verify
      DATABASE_SCHEMA: verify
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      INJI_VP_REQUEST_LONG_POLLING_TIMEOUT: 55000
      INJI_VP_SUBMISSION_BASE_URL: https://VERIFY_SERVICE_PROXY_FOR_LOCALHOST/v1/verify
      INJI_DID_VERIFY_URI: did:web:VERIFY_SERVICE_PROXY_FOR_LOCALHOST:v1:verify
      INJI_DID_VERIFY_PUBLIC_KEY_URI: 'did:web:VERIFY_SERVICE_PROXY_FOR_LOCALHOST:verify#key-0'
      INJI_KEYSTORE_FILE_PASS: mosip
      INJI_VERIFY_REDIRECT_URI: https://VERIFY_SERVICE_PROXY_FOR_LOCALHOST
      INJI_VERIFY_RESPONSE_CODE_EXPIRY_TIME_IN_MINS: 5
      INJI_VERIFY_CLAIMS_WITH_META_DATA: _sd,_sd_alg,iss,cnf,sub,aud,exp,nbf,iat,cti
      VERIFY_CONTEXT_PATH: /v1/verify
    networks:
      - conformance-net
    depends_on:
      - verify-postgres

  # =========================
  # OPENID CONFORMANCE SUITE
  # =========================

  conformance-mongodb:
    image: mongo:6.0.13
    volumes:
      - ./conformance-suite/mongo/data:/data/db
    networks:
      - conformance-net

  server:
    image: registry.gitlab.com/openid/conformance-suite:release-v5.3.1
    environment:
      BASE_URL: https://localhost.emobix.co.uk:8443
      BASE_MTLS_URL: https://localhost.emobix.co.uk:8444
      MONGODB_HOST: conformance-mongodb
      SPRING_PROFILES_ACTIVE: dev
      OIDC_GOOGLE_CLIENTID: google-client
      OIDC_GOOGLE_SECRET: google-secret
      OIDC_GITLAB_CLIENTID: gitlab-client
      OIDC_GITLAB_SECRET: gitlab-secret
    networks:
      - conformance-net
    depends_on:
      - conformance-mongodb

  conformance-nginx:
    image: registry.gitlab.com/openid/conformance-suite/nginx:release-v5.3.1
    ports:
      - "8443:8443"
      - "8444:8444"
    networks:
      conformance-net:
        aliases:
          - localhost.emobix.co.uk
    depends_on:
      - server

networks:
  conformance-net:
    name: openid-conformance-net
